name: Deployment CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - run: mv out portfolio # rename out to portfolio
      - run: rm -rf /var/www/html/portfolio # remove directory that isnt empty
      - run: mv portfolio /var/www/html # move portfolio folder to another directory
